### ISSUE TITLE
Versionierung von YFeed fortführen? 

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/feeds#100]
@gharlan  @tbaddade 

Was meint Ihr? Mit 1.0 starten oder die Version von YFeed fortführen?
Da sich jetzt tatsächlich einiges geändert hat (z.B. andere Vendoren, neue Methoden) , würde ich schon auf 2.0 gehen.

**Comment by alexplusde** [comment]
Wir sind im selben repo, ich würde die 2 nehmen.

**Comment by schuer** [comment]
Für mich wäre es auch eindeutig eine 2. Allein schon, weil sich der AddOn-Key geändert hat, was bereits ein BC wäre.

**Comment by skerbis** [comment]
Ok

**Comment by gharlan** [comment]
1.x fortführen würde ich auch nicht. Mit 1.0 neu beginnen fände ich ok, wenn man es so betrachtet: Neuer Name -> neues Addon -> neue Versionisierung.
Präferieren würde ich aber auch 2.0.

**Comment by skerbis** [comment]
Dann wird´s ne 2.0
