### ISSUE TITLE
Fehler beim Import von yFeed

### ISSUE THREAD

**Issue by adamengineering** [FriendsOfREDAXO/feeds#102]
<img width="1016" alt="screenshot" src="https://user-images.githubusercontent.com/23257336/58782113-f10df080-85dd-11e9-9c97-e6894c06d73d.png">

Folgende Fehlermeldung erscheint, wenn ich versuche Feeds zu installieren und in den bestehenden yFeed Tabellen keine Einträge vorhanden sind.

**Comment by skerbis** [comment]
@gharlan hast du eine Idee, wie man das abfangen kann?

**Comment by gharlan** [comment]
Hmm, der Fehler erschließt sich mir noch nicht, gerade wenn die Tabellen leer sind. Gemeckert wird ja über "Duplicate key on write or update" (ganz am Ende der Meldung).

**Comment by gharlan** [comment]
Ich habe es jetzt getestet, und das Problem müsste eigentlich jeder bekommen bei der Migration.

Das Problem ist, dass schon ein Constraint "stream_id" existiert, und dann versucht rex_sql_table einen neuen Fremdschlüssel unter gleichem Namen anzulegen, der zu der Feeds-Tabelle zeigt (der schon existierende zeigt zur yfeed-Tabelle).
Im Migrationsfall müsste also der vorhandene Fremdschlüssel scheinbar explizit gelöscht werden.
Zum Beispiel über `rex_sql_table::get(...)->removeForeignKey('stream_id')->alter()` oder so.

Wobei das ein Bug im Core zu sein scheint, dass das hier nicht automatisch passiert. Ich lege dazu ein Issue an.

Ich hätte immer noch besser gefunden, die Struktur der Tabellen nicht aus den alten Tabellen zu generieren, sondern direkt frisch so anzulegen, wie sie sein soll. Dann hätte man hier auch nicht das Problem mit dem alten Fremdschlüssel, der dann noch zur alten Tabelle zeigt.

**Comment by skerbis** [comment]
Verstehe nicht warum das bei meinen Tests nicht aufgefallen ist. Seltsam. Kann das heute leider nicht fixen. Bin unterwegs.

**Comment by gharlan** [comment]
Sorry, meine Analyse oben war Quatsch!
Das Problem ist ein anderes, Constraints brauchen eindeutige Namen über alle Tabellen hinweg. Und der Name "stream_id" beim Foreignkey wird ja schon verwendet von der yfeed-Tabelle.
Lösung: Hier als ersten Parameter etwas anderes nehmen, zum Beispiel "feeds_item_stream_id": 
https://github.com/FriendsOfREDAXO/feeds/blob/9473754653ac3a71f21be99050761541b58e10b8/install.php#L101

**Comment by skerbis** [comment]
@gharlan @adamengineering  ich habe jetzt noch mal eine Installation mit einem leeren YFeed getestet und sehe sehe bei der Installation der feeds 2.0 kein Problem. Der o.g. Fehler tritt bei mir nicht auf.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/feeds/releases/tag/2.0.1
