### ISSUE TITLE
Instagram - mehr als 20 Beiträge abrufbar machen

### ISSUE THREAD

**Issue by greatif** [FriendsOfREDAXO/feeds#103]
Die Instagram-API begrenzt den Abruf auf nur dann auf **max. 20 Beiträge**, wenn der verwendete Access-Token zu einer App gehört, im sog. **Sandbox-Modus** _(Entwickler-Modus)_ läuft _(d.h. die App noch nicht verifiziert ist)_.
Gehört der verwendete Access-Token zu einer _(verifizierten)_ App im Live-Modus, gelten diese Limitierungen nicht. Es lassen sich dann paketweise **jeweils 33 Beiträge** abrufen, wobei man über den Paramteter `pagination->next_max_id` dann den URL zum Abruf der nächsten 33 Beiträge generieren kann.
Evtl. macht es doch Sinn, dass man über die Einstellungen mehr als 20 Beiträge _(bei geeignetem Token)_ abrufen kann, denn ggf. möchte man initial bereits veröffentlichte Beiträge in größerer Zahl zunächst in der DB archivieren.

![Instagram](https://user-images.githubusercontent.com/8527203/58893747-0293ed00-86f1-11e9-9b83-f9982d83999d.png)

**Comment by skerbis** [comment]
Also zusätzlich erstmal noch ein Auswahlfeld mit 33 dazu? Oder was schlägst du genau vor?

**Comment by alexplusde** [comment]
Ich habe das in Instagram nicht verifiziert bekommen, es müsste auf jeden Fall auch eine Anleitung dazu, welche URLs bei Instagram hinterlegt werden müssen, damit der Abruf funktioniert.

**Comment by alexplusde** [comment]
Und zusätzlich scheint es so, dass alles auf die Facebook-API hinauslaufen wird längerfristig, also ist die Frage, ob man das nicht grundsätzlich überarbeiten muss.

**Comment by greatif** [comment]
@skerbis naja, durch die oben beschriebene Paginations-Funktion kann man "seitenweise" bis zu je 33 Beiträge abrufen, bis hin zu allen vorhandenen Beiträgen.
Ob man da jetzt eine Vorauswahl "5, 10, 25, 50" oder "5, 10, 33, 66" oder was auch immer ermöglicht, ist wohl Geschmackssache.
Interessant fände ich, wenn es die Option gäbe, dass beim ersten Abruf erstmal alle vorhandenen Beiträge archiviert werden.
**Ein Beispiel aus einem Modul für den Abruf von X bis Alle Beiträge:**
```
<?php
$access_token = REX_VALUE[1];
$userid = substr(REX_VALUE[1], 0, 10);

// Wenn die Anzahl der auszugebenden Beiträge (REX_VALUE[2]) größer ist, als der max. Seiten-Count-Wert 33, dann (für die erste abzurufende Seite) den Count auf den Maximalwert 33 setzen
$count = REX_VALUE[2];
if ($count > 33 OR $count == 'alle') {
	$count = 33;
}

$api_url = 'https://api.instagram.com/v1/users/'.$userid.'/media/recent/?access_token=REX_VALUE[1]&count='.$count.'';
$output = '';
$counter = 0;

// Verbindung zur Instagram-API herstellen, um erste Seite abzurufen
$curl = curl_init();
curl_setopt_array($curl, array(
  CURLOPT_RETURNTRANSFER => 1,
  CURLOPT_URL => $api_url,
  CURLOPT_TIMEOUT => 20,
  CURLOPT_SSL_VERIFYPEER, 1
 ));
// Anfrage absenden, Antwort-Daten im JSON-Format in $data speichern und Verbindung beenden
$json_decode = curl_exec($curl);
$data = json_decode($json_decode, true);
curl_close($curl);
// URL der nächsten Seite
$next_url = $data['pagination']['next_url'];

// dump($data);

// Wenn Antwort-Daten vorhanden sind
if($json_decode){
	$output .= '
		<div class="row">
			<hr /><h2 class="text-center title-uppercase">Instagram</h2><br>';

	// Ausgabe für jeden abgerufenen Beitrag der ersten Seite		
	foreach((array)$data['data'] as $images){
		$output .= '
			<div class="text-center col-md-2 col-sm-3 col-xs-6 instagram">
				<a href="'.$images['link'].'" ><img src="'.$images['images']['thumbnail']['url'].'" alt="'.$images['id'].'"/><p><i class="fa fa-heart"></i> '.$images['likes']['count'].' | <i class="fa fa-comment"></i> '.$images['comments']['count'].'</p></a>
			</div>';
		// Anzahl der (insgesamt) ausgegebenen Beiträge zählen
		$counter++;
	}

	// Wenn die Anzahl der bisher ausgegebenen Beiträge noch kleiner ist, als die Anzahl der Beiträge, die insgesamt ausgegeben werden sollen, dann erneut Verbindung zur Instagram-API herstellen u. über d. URL der nächsten Seite weitere Beiträge abrufen
	if ($counter < REX_VALUE[2] OR REX_VALUE[2] == 'alle') {
		// ...solange, wie eine weitere Seite existiert
		while ($next_url) {
			$curl = curl_init();
			curl_setopt_array($curl, array(
				CURLOPT_RETURNTRANSFER => 1,
				CURLOPT_URL => $next_url,
				CURLOPT_TIMEOUT => 20,
				CURLOPT_SSL_VERIFYPEER, 1
			));
			$json_decode = curl_exec($curl);
			$data = json_decode($json_decode, true);
			curl_close($curl);
			// URL der nächsten Seite
			$next_url = $data['pagination']['next_url'];
		
			// dump($data);
		
			if($json_decode){
				foreach((array)$data['data'] as $images){
					// ...solange, bis die Anzahl der abzurufenden Beiträge erreicht ist
					if ($counter < REX_VALUE[2] OR REX_VALUE[2] == 'alle') {
						$output .= '
							<div class="text-center col-md-2 col-sm-3 col-xs-6 instagram">
								<a href="'.$images['link'].'" ><img src="'.$images['images']['thumbnail']['url'].'" alt="'.$images['id'].'"/><p><i class="fa fa-heart"></i> '.$images['likes']['count'].' | <i class="fa fa-comment"></i> '.$images['comments']['count'].'</p></a>
							</div>';
						$counter++;
					}
				}
		
			}
		}
	}

	$output .= '
		</div>';
		
	echo $output;
	
} else {
	echo "FEHLER";
}

?>
```

@alexplusde was meinst Du mit "Ich habe das in Instagram nicht verifiziert bekommen"? Du musst Deine App doch von Instagram "reviewen" lassen, um aus dem (limitierten) Sandbox-Modus rauszukommen und live gehen zu können.
![insta](https://user-images.githubusercontent.com/8527203/58942165-88f61080-877d-11e9-8fad-e7b4ce527566.png)
Bist Du daran gescheitert?
Alternativ kannst Du Dir ja einen nicht-limitierten Access-Token über **outofthesandbox.com/pages/instagram-access-token** oder **instagram.pixelunion.net** holen.
Wir kommst Du darauf, dass bald alles auf die Facebook-API hinauslaufen wrid?

**Comment by alexplusde** [comment]
> Du musst Deine App doch von Instagram "reviewen" lassen, um aus dem (limitierten) Sandbox-Modus rauszukommen und live gehen zu können.

Ja, daran bin ich gescheitert, denn "my app allows people to login with instagram" ist ja quatsch und es bei "i want to display my instagram posts on my website" wird explizit der Sandbox-Modus empfohlen.

**Comment by greatif** [comment]
> Ja, daran bin ich gescheitert, denn "my app allows people to login with instagram" ist ja nicht zutreffend und bei "i want to display my instagram posts on my website" wird explizit der Sandbox-Modus empfohlen.

Dann bleibt letztlich nur das Verwenden eines nicht-limitierten Access-Tokens eines Fremdanbieters.
Es sollte dann m.E. auf der Feeds-Einstellungsseite für den Instagram Access-Token ein Hinweis vorhanden sein, dass beim Verwenden eines Access-Tokens einer Sandbox-App das Abruf auf 20 Beiträge beschränkt ist und evtl. ein weiterer Hinweis, dass es über Drittanbieter die Möglichkeit gibt, einen nicht-limitierten Access-Token zu beziehen.

**Comment by skerbis** [comment]
Also @greatif es gibt Tokens anderer Anbieter, die das erlauben? Also müsste man dann erstmal hier nichts mehr ändern und nur die Auswahl wieder anpassen? Wenn ja, magst du in der Readme beschreiben wie man diese Tokens bekommt?

**Comment by greatif** [comment]
@skerbis ein einfaches "Ja" greift als Antwort zu kurz, glaube ich: Es kommt darauf an, ob die jeweilige App _(egal, ob eine eigene oder die eines Fremdanbieters)_ im Sandbox-/Entwickler-Modus oder - nach Review durch Instagram - verifiziert im Live-Modus läuft. Läuft eine App im Sandbox-Modus, dann ist Daten-Abruf - mittels Access-Token - über die Insta-Api beschränkt. Läuft die App im Live-Modus, erhält man vollen Zugriff.
Das bedeutet, dass Fremdanbieter eine durch Insta verifizierte App haben, für die man über deren Webseite einen Access-Token generieren lassen kann. Man muss dann der App den Zugriff auf den jeweiligen Insta-Account gestatten und kann dann über den generierten Access-Token dann - uneingeschränkt - Beiträge abrufen.
Solche Anbieter sind z.B.:
**outofthesandbox.com/pages/instagram-access-token
instagram.pixelunion.net**

Solche Anbieter sind, dann eine Alternative, wenn man, wie z.B. @alexplusde Probleme hat, dass die eigene App aus dem Sandbox-Modus rauskommt, als reviewed wird.

Ob es einfach damit getan ist, einfach die Auswahl anzupassen, weiss ich nicht.
Das hängt davon ab, wie "Feeds" die Beiträge abruft. Durch die Pagination bekommst Du bei einem einfachen Abruf erstmal max. nur 33 Beiträge. Im Array Der gelieferten Daten ist aber ein Link "zur nächsten Seite" bzw. zu den nächsten 33 Beiträgen, den du dann wieder abrufen kannst.
In einer Schleife kannst Du dann alle Seiten abrufen.
Je nachdem, wie Du den Abruf baust, kannst Du dann die Auswahl anpassen.

Wegen der Readme:
Das mit dem Access-Token eines Fremdanbieters funzt ganz einfach. Sie auf dem Screenshot unter **Punkt B.**:
![insta](https://user-images.githubusercontent.com/8527203/59098109-b67abf80-891f-11e9-8bc4-6ccda6aa9bc3.png)

**Comment by skerbis** [comment]
Tatsächlich ist der hier mitgelieferte vendor https://github.com/galen/PHP-Instagram-API
ewig nicht mehr weiterentwickelt worden und es fehlt eben an max id oder prev. Wir sollten Ausschau nach einem Ersatz halten.

**Comment by greatif** [comment]
@skerbis hab mir den Verndor mal kurz angeschaut. Ist zwar tatsächlich schon etwas älter, aber der Abruf über die Pagination via `max_id` scheint schon unterstützt zu werden:
![insta](https://user-images.githubusercontent.com/8527203/59101852-97cdf600-892a-11e9-89c4-c49276aaaf59.png)
Weiß also nicht, ob wirklich einen neuen Vendor benötigt...

**Comment by skerbis** [comment]
Ich stelle es wieder auf die frühere Auswahl zurück. Anscheinend funktioniert es ja mit Fremd-Tokens.

**Comment by alexplusde** [comment]
@skerbis mach doch ein number-Feld daraus mit default 20. Dann ist jeder frei.

**Comment by alexplusde** [comment]
@greatif da du schon so viele Erfahrungen mit deinem eigenen Modul gesammelt hast - wärst du ggf. bereit, die beiden Streams umzubauen? Wenn ich das richtig sehe, ist man auf die Vendoren überhaupt nicht angewiesen, wennn man die API direkt aufruft.

Man müsste nur sicherstellen, dass die Felder am Ende wieder exakt gleich befüllt werden...

**Comment by alexplusde** [comment]
@greatif was meinst du zu meinem Vorschlag?

**Comment by greatif** [comment]
@alexplusde jap, auf die Vendoren kann man grds. verzichten, wenn man die API direkt aufruft.
Mein Modul ist ganz elementar gehalten: Man gibt den Access-Token eines Accounts ein und wählt aus, ob man 12, 24, 33, 66 oder alle Beiträge abrufen möchte.
Ich weiss nicht, ob das Deinen Vorstellungen entspricht. Statt die Beträge direkt auszugeben, kann man sie natürlich auch in eine DB schreiben. Vllt. solltest d. Modul erstmal testen bzw. testweise in d. AddOn einbinden, um zu sehen, ob Dir das überhaupt weiterhilft.

**Comment by alexplusde** [comment]
Ja, ich dachte schon, dass du vllt einen PR hier machen möchtest?

**Comment by alexplusde** [comment]
Ich habe vorerst eingebaut, alle (bis zu 1000 Einträge) abrufbar zu machen.

In Zukunft scheint man ohnehin über die Facebook Instagram Graph und Display API gehen zu müssen. Das ist dann wieder ein eigenes Kapitel.
