### ISSUE TITLE
setValue()-Methode für Items

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/feeds#105]
Jedes Feld in der Items-Tabelle hat eine eigene Methode zum einfügen. Ich würde es bevorzugen, wenn es auch eine eigene setValue()-Methode gäbe, wenn man in einem Feed-Profil eigene Datenbank-Felder hinzufügen möchte, ohne die Klasse deswegen erweitern / abwandeln zu müssen

Beispiel: ein Rating-Feld für eine Bewertung eines Kundenrezensionen-Feeds von Facebook, Google Places, o.a.

**Comment by skerbis** [comment]
ich frage mich ob das notwenig ist, die Tabelle ständig zu erweitern. Wäre es nicht sinnvoller ein JSON oder YAML Feld zu haben?

**Comment by alexplusde** [comment]
Wenn du per SQL danach suchen oder filtern willst, kommst du nicht durm herum. ein JSON-Feld zum Ablegen der RAW-Daten gibt's bereits.

**Comment by skerbis** [comment]
> MySQL 5.7 InnoDB and PostgreSQL 9.4 databases both directly support JSON document types in a single field. 

und diese kannst du auch z.b mit WHERE JSON_CONTAINS durchsuchen

**Comment by skerbis** [comment]
Das RAW-Feld ist kein JSON-Feld. Da kann alles mögliche drin landen

**Comment by alexplusde** [comment]
Ah. Ich hab hier noch MySQL5.6 beim Provider...

**Comment by skerbis** [comment]
na ja einen kleinen Tod ...
