### ISSUE TITLE
Methode setStatus() zusätzlich zu setOnline()

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/feeds#106]
Das Feld heißt `status`, demzufolge erwartet man auch eine Methode namens setStatus()

**Comment by skerbis** [comment]
PR welcome

**Comment by tbaddade** [comment]
> Das Feld heißt status, demzufolge erwartet man auch eine Methode namens setStatus()

Nicht unbedingt. ein 

`setOnline` kann nur bool sein und könnte intern dann wieder `setStatus` aufrufen
`setStatus` kann dagegen irgendetwas sein

**Comment by alexplusde** [comment]
Wenn man bei der Argumentation bleibt, ist es quatsch, `setOnline(0)` ausführen zu können. 
Dann eben keine Alias-Methode. `setStatus($value)` wäre trotzdem korrekt und die gibt es nicht.

**Comment by tbaddade** [comment]
>  ist es quatsch, setOnline(0) ausführen zu können.

Warum ist das quatsch? Aber ich bin jetzt hier raus …

**Comment by alexplusde** [comment]
Dann habe ich nicht verstanden, warum man `setOnline()` und `setStatus()` unterschiedlich behandeln sollte. 

`setOnline()` benötigt doch gar keinen Parameter, weil `setOnline(0)` würde doch keiner schreiben, dazu bräuchte man dann `setOffline()`.

**Comment by skerbis** [comment]
Ich schließe mich @tbaddade an: 

setOnline() legt den Online-Status (bool) fest. 

setStatus() würde ich verwenden wenn ich neben online auch gesperrt oder wartend oder sonstwas hätte. 

Wir sollte setStatus() nicht für einen Alias verschwenden.

**Comment by alexplusde** [comment]
Dann bitte möge man mein Issue dahingehend intepretieren, dass ich eine Methode setStatus() vorschlage, die genau das umsetzt.

**Comment by alexplusde** [comment]
Ich denke nicht, dass ich hier nochmal etwas machen werde und es scheint sonst keinen zu stören.
