### ISSUE TITLE
Weitere Kurzanleitungen für verschiedene Quellen (Instagram, Vimeo, ...)

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/feeds#109]

**Comment by alexplusde** [comment]
PR welcome

Ich bin daran gescheitert, mit API-Schlüssel an Instagram-Bilder zu kommen. Ohne kann man bis zu 20 direkt abrufen, dafür braucht es keine Anleitung imho.

**Comment by tbaddade** [comment]
> Was klappt nicht, dass es eine Doku rechtfertigt?

Ich schließe … Sorry

**Comment by alexplusde** [comment]
An sich schon legitim, im Vorfeld zu lesen, was einen erwartet, wenn man das Addon noch nicht benutzt hat. Ich habe den Titel des Issues mal angepasst. Ist auch was für Einsteiger

**Comment by ynamite** [comment]
Gerade versucht das Addon für Insta zu nutzen. Funzt nicht und keinen Plan was ich falsch mache.

Ohne API: "Account with this username does not exist" egal welchen Account-Namen ich verwende.
Mit API: keinen Plan wie ich an einen API-Schlüssel komme.

Eine Anleitung wäre schon cool.

**Comment by alexplusde** [comment]
Gerne in Slack nachforschen und vorformulieren, ich kann Korrekturlesen anbieten.

**Comment by ynamite** [comment]
@alexplusde ist das an mich gerichtet?

**Comment by ynamite** [comment]
@alexplusde Wow.

**Comment by skerbis** [comment]
Habe nun ein paar ergänzt. Gerne mehr.

**Comment by tbaddade** [comment]
@skerbis Es hilft uns, wenn du in deinen Commits ein `#109` oder `close #109` oder `fixed #109` notierst. Dann kann man vom Issue direkt dorthin springen.

**Comment by skerbis** [comment]
@tbaddade die Änderungen habe ich nicht wg. der issues gemacht. Ich habe später geschaut ob irgendwelche Issues zutreffen. Aber danke für den Tipp. Werde mich (wieder) daran halten.
