### ISSUE TITLE
Extension Point nach dem erfolgreichen Abruf eines Streams

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/feeds#129]
Siehe
https://redaxo.org/doku/master/extension-points#definieren

z.B., um im Anschluss URLs zu generieren o.ä.

**Comment by alexplusde** [comment]
Ich habe dazu jetzt mal einen Vorschlag für 2 EPs gemacht - der Pro Stream wäre für das URL-Addon sicher besonders relevant.

Da ich EPs noch nie selbst erstellt habe und die Doku dahingehend zwar gut ist, aber das Thema mir nicht vertraut, bitte ich um Untersützung.

**Comment by alexplusde** [comment]
@pschuchmann würde den PR gerne fertig machen. Taugt das so für dich?

**Comment by pschuchmann** [comment]
Finde ich sehr gut so, danke dir fürs Umsetzen!
