### ISSUE TITLE
Wording: Stream/Profil/Quelle

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/feeds#135]
Mir ist aufgefallen, dass im Kontext von Feeds gerne von Streams geschrieben wird, aber ich hätte gerne einen deutschen Begriff an der Stelle. Was wäre besser:

* `Stream` behalten
* `Quelle` / `Datenquelle`
* `Profil`

Ich bin für Quelle.

**Comment by skerbis** [comment]
- Stream ist aber schon etabliert.  
- Datenstrom
- Datenfluss
- Datenliste 
...

**Comment by alexplusde** [comment]
Etabliert wo? Sagen wir, jemand, der Feeds noch nicht kennt, was würde diese Person am besten verstehen? Datenstrom/fluss finde ich doch sehr abstrakt.

**Comment by skerbis** [comment]
Aber das ist es nun mal. Man bekommt einen Datenstrom , Feed oder Stream eines Anbieters

**Comment by skerbis** [comment]
Alternativ nenne es Kanal

**Comment by tbaddade** [comment]
> Stream behalten

👍
