### ISSUE TITLE
Stream kann nicht angelegt werden - Fehler beim speichern

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/feeds#144]
**Version 3.1-beta2**

<del>Leider erkennt man nicht den genauen Fehler.</del>

> Cannot add or update a child row: a foreign key constraint fails (`db1`.`rex_feeds_stream`, CONSTRAINT `rex_feeds_stream_ibfk_1` FOREIGN KEY (`id`) REFERENCES `rex_feeds_item` (`stream_id`) ON DELETE CASCADE ON UPDATE CASCADE)

Siehe Screenshot.

<img width="987" alt="Bildschirmfoto 2020-01-21 um 15 32 39" src="https://user-images.githubusercontent.com/338267/72813294-64469e80-3c63-11ea-859e-c31e172d4bcf.png">

**Comment by alexplusde** [comment]
Wenn ich's recht auf dem Schirm habe, ist das durch einen ungewollten Foreign Key in einer vorherigen Version so passiert. Bitte übergangsweise den genannten Foreign Key löschen. Ich muss mich noch kundig machen, wie ich den wieder weg bekomme.

**Comment by alexplusde** [comment]
Wenn ich's recht auf dem Schirm habe, ist das durch einen ungewollten Foreign Key in einer vorherigen Version so passiert. Bitte übergangsweise den genannten Foreign Key löschen. Ich muss mich noch kundig machen, wie ich den wieder weg bekomme.

**Comment by alexplusde** [comment]
gelöst in https://github.com/FriendsOfREDAXO/feeds/pull/148
