### ISSUE TITLE
Styles auslagern

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/feeds#145]
Wie zum Bsp. diese hier, damit man besser darauf reagieren kann.
https://github.com/FriendsOfREDAXO/feeds/blob/master/pages/items.php#L104
https://github.com/FriendsOfREDAXO/feeds/blob/master/pages/items.php#L113

Nebenbei bemerkt, empfinde ich den Hintergrund bei den Thumbnails als zu dunkel.

**Comment by alexplusde** [comment]
Ich würde das lieber gemeinsam hiermit umgesetzt sehen #74

**Comment by tbaddade** [comment]
#74 ist bereits closed.

**Comment by alexplusde** [comment]
Stimmt, das war nicht mehr offen. Hatte ich jedoch als Meilenstein und Branch bereits angelegt und vor.

**Comment by alexplusde** [comment]
@tbaddade würdest du hier was beisteuern wollen?

**Comment by tbaddade** [comment]
> würdest du hier was beisteuern wollen?

Ich würde gern Anderen den Vorzug geben wollen. Wir gaben das AddOn auch zu FOR, damit wir weniger daran involviert sind. Wenn es wirklich klemmen sollte, mache ich es gern..

**Comment by alexplusde** [comment]
Ja, das verstehe ich, und das würde ich mir auch wünschen.

**Comment by skerbis** [comment]
Geht hier weiter: https://github.com/FriendsOfREDAXO/feeds/issues/188
