### ISSUE TITLE
Update von yfeed 1.3.0

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/feeds#152]
Fehlt hier nicht in der Zeile ein `=` also `<= 1.3.0`?
https://github.com/FriendsOfREDAXO/feeds/blob/master/package.yml#L39

**Comment by alexplusde** [comment]
Soweit ich weiß, ist das richtig. Denn für die Umstellung von yfeed auf feeds müssen beide installiert sein.

**Comment by tbaddade** [comment]
> Soweit ich weiß, ist das richtig. Denn für die Umstellung von yfeed auf feeds müssen beide installiert sein.

Korrekt. Da du aber die Migration [hier](https://github.com/FriendsOfREDAXO/feeds/commit/af773c2b3b79c759cf21c0e1bf2bf9ee08dd07c5#diff-3b7de2cf163f18aa521c050bb543084f) entfernt hast, müsste der conflict angepasst werden. Außerdem wird grad diese wichtige Info, dass die Migration entfernt wurde, im Changelog nicht erwähnt.

**Comment by alexplusde** [comment]
closed via #f0e5164
