### ISSUE TITLE
Neue Facebook-Apps arbeiten nur mit API 6.0

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/feeds#153]
Auswählen kann man beim Stream aber nur bis API-Version 3.2

**Comment by alexplusde** [comment]
Der Vendor gibt das meiner Erinnerung nach nicht her, da er nicht weiterentwickelt wird Ich könnte das aktuell nicht fixen.

Workaround: Abruf über Drittanbieter per RSS

**Comment by alexplusde** [comment]
Siehe auch #153

**Comment by tbaddade** [comment]
> Der Vendor gibt das meiner Erinnerung nach nicht her, da er nicht weiterentwickelt wird Ich könnte das aktuell nicht fixen.

Hast du schon mal die 5er Version probiert?
https://github.com/facebook/php-graph-sdk
Oder ist die als Vendor schon dabei? Kann grad via Phone nicht wirklich nachsehen?

**Comment by alexplusde** [comment]
Bin auch am Smartphone gewesen...

Die ist als Vendor mit dabei, auch 5.7. Hier sind mir generell viel zu viele Abhängigkeiten drin, deswegen blicke ich da nicht so durch: 
![image](https://user-images.githubusercontent.com/3855487/73776664-773f8f80-4788-11ea-9485-46a045bdecb8.png)

Und in meiner Erinnerung wurden nach facebook sdk `3.2` Änderungen an der Authentifizierung angekündigt. Hast du mal probiert, die `6.0` einzustellen und abzurufen? Funktioniert das dann?
