### ISSUE TITLE
Cronjob - alle Streams oder direkt wählen

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/feeds#155]
Aktuell muss man Streams bei einem Cronjob ausschließen. Kommt in der Zwischenzeit ein neuer Stream hinzu, muss man auch immer wieder daran denken diesen in der Liste hinzuzufügen.

Dieses Verhalten ist inkonsequent zu anderen Auswahlfeldern.

Schön wäre das gleiche Verhalten wie es bei den Rechten umgesetzt ist.
Checkbox für Alle Streams oder multiple select um einzelne Streams auszuwählen.

Ob das aktuell umgesetzt werden kann oder ob hier erst einmal im Cronjob AddOn Anpassungen vorgenommen werden müssen habe ich nicht geprüft.

**Comment by alexplusde** [comment]
Kann hier umgesetzt werden. Ich habe mich bewusst für diese Lösung entschieden, weil ich von folgendem Workflow ausgegangen bin:

* Ein Cronjob ruft alle Streams ab
* nur zeitintensive oder häufig abzurufende Streams werden aus Performancegründen rausgenommen und separat angelegt.

**Comment by tbaddade** [comment]
Wäre beides dann noch möglich

> Ein Cronjob ruft alle Streams ab

Checkbox "Alle" ist angehakt

> nur zeitintensive oder häufig abzurufende Streams werden aus Performancegründen rausgenommen und separat angelegt.

Separater Cronjob mit Auswahl des Streams

Problematisch wird es, wenn man beides benötigt. Aber das ist aktuell auch bei den anderen Auswahlfeldern so. Das soll nicht heißen das ich das gut finde wie der Status quo ist. Ich fände nur das gleiche Verhalten angebracht. Zum Beispiel vergesse ich immer das neue Modul auch der Rolle zuzuweisen.

**Comment by alexplusde** [comment]
Ja, da könnte man sich mal eine Lösung zu überlegen oder vlt. beim Anlegen des Streams daran erinnern.

**Comment by alxndr-w** [comment]
Mit https://github.com/alexplusde/collect/ habe ich hier einen m.E. zielführenden Ansatz gewählt - ein Stream ist ein Cronjob.

**Comment by skerbis** [comment]
In 4.0 wird die Blacklist entfernt und es werden nur die ausgewählten oder alle Streams abgerufen.

**Comment by skerbis** [comment]
Ich denke man könnte einen allgemeinen Cronjob anlegen, der in einem festgelegten Intervall arbeitet und die Zeitsteuerung direkt in Feeds selbst machen.
