### ISSUE TITLE
Instagram: Account with this username does not exist

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/feeds#159]
Scheinbar wurde nun auch die API zu Instagram verändert.

**Comment by rkemmere** [comment]
Hey, was muss denn gemacht werden, damit das Ding wieder läuft?

**Comment by alexplusde** [comment]
Ein PR hier im Addon, der das Problem löst.

**Comment by pschuchmann** [comment]
Vielleicht kann man sich hier langhangeln.
https://developers.facebook.com/blog/post/2020/03/10/final-reminder-Instagram-legacy-api-platform-disabled-mar-31/

**Comment by rkemmere** [comment]
Oder das hier nutzen? https://github.com/espresso-dev/instagram-basic-display-php

**Comment by alexplusde** [comment]
Siehe auch https://github.com/FriendsOfREDAXO/feeds/issues/139

Wie gesagt, von mir wird hier aktuell kein Fix kommen. Es wäre super, wenn die beiden Instagram und Facebook Feeds mit aktuellen Vendoren oder mit direktem Zugriff auf die API wieder möglich sind.

**Comment by palber** [comment]
@pschuchmann 
Der Quick & Dirty Fix funkioniert bei mir auch auf einem all-inkl Server.

**Comment by skerbis** [comment]
Da sich einiges ändern wird schließe ich hier. Danke an die Beteiligten
