### ISSUE TITLE
Laden von Bildern von Facebook Feeds

### ISSUE THREAD

**Issue by eherwig** [FriendsOfREDAXO/feeds#163]
Im Typ "Facebook Feed" werden keine Bilder zu den Posts heruntergeladen.

Addon-Version: 3.1
eingestellte API-Version: 3.2

Lösung:

In der Datei `/redaxo/src/addons/feeds/lib/stream/facebook_feed.php`, Zeile 111, muss

`switch ($facebookItem->getField('type')) {`

durch

`switch ($attachment->getField('type')) {`

ersetzt werden.

**Comment by alxndr-w** [comment]
Hi @eherwig, danke für die Info und den Lösungsweg! 

Wusstest du, dass du solche Korrekturen hier auf GitHub direkt bearbeiten und als Pull-Request einreichen kannst? Wenn du es mal ausprobieren möchtest, klicke auf den nachfolgenden Link und folge den Anweisungen:

https://github.com/FriendsOfREDAXO/feeds/edit/master/lib/stream/facebook_feed.php

Ist dasselbe, wie wenn du hier im GitHub-Repository von feeds auf "Code" gehst und dann weiter durchklickst bis zum Bearbeiten der Datei:

![image](https://user-images.githubusercontent.com/3855487/146806705-cb63d9cd-2f77-4c13-a182-6fb527991852.png)

**Comment by skerbis** [comment]
Da sich einiges ändern wird schließe ich hier. Danke an die Beteiligten
