### ISSUE TITLE
Warning: Undefined array key "media" wenn der Cronjob läuft

### ISSUE THREAD

**Issue by rolandsee** [FriendsOfREDAXO/feeds#177]
Feeds Version:  3.3.0-beta1
PHP 8.0.19
Redaxo 5.13.3

Wenn der Cronjob (wie in meinem Fall einmal täglich) läuft, werden viele Warnings im Logfile aufgezeichnet. Wenn ich z.B. 50 Beiträge aus dem jeweiligen Feed abhole, bekomme ich 50 Warnings. Das kann unter Umständen zu einem sehr großen Logfile führen.

![image](https://user-images.githubusercontent.com/4113894/173039565-a6a7d40f-e688-4668-8ace-963a2e06f5f5.png)

![image](https://user-images.githubusercontent.com/4113894/173040033-9f2be253-212c-445c-8987-bfeb490bb685.png)

Im vorliegenden Fall wird ein Feed der Datev abgeholt: https://www.datev-magazin.de/nachrichten-steuern-recht/feed

**Comment by skerbis** [comment]
Danke, das wird sich mit 4.0 ändern

**Comment by skerbis** [comment]
Picofeed wird es ab Version 4 nicht mehr geben.
