### ISSUE TITLE
RSS Bridge als Basis?

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/feeds#182]
**Feature description / Feature Beschreibung**

https://github.com/RSS-Bridge/rss-bridge bietet einige interessante [Brücken](https://github.com/RSS-Bridge/rss-bridge/tree/master/bridges), z.B. Twitter, [Telegram](https://github.com/RSS-Bridge/rss-bridge/blob/master/bridges/TelegramBridge.php) etc. Vielleicht kann man das irgendwie integrieren oder ermöglichen, dass diese Bridges auch hier funktionieren?

**Comment by skerbis** [comment]
@cukabeka ich habe es getestet. Facebook scheint damit aber auch nicht zu funktionieren. Twitter ging sofort. 
Die Bridges würden funktionieren, da es JA RSS-Feeds, JSON-Feeds und ATOM-Feeds erstellt. 

Danke für den Tipp.
