### ISSUE TITLE
4.0

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/feeds#186]
Ich habe die Arbeiten an 4.0-dev begonnen. 

1. Ich teste neue Vendoren für RSS und ATOM
2. Die Vimeo-Umsetzung ist überarbeitet. Liest nun auch die Preview-Images aus und lädt optional alle oder nur öffentliche  Video-Links. 
3. Alles was sonst nicht mehr funktioniert habe ich entfernt
4. Liste kann nun sortiert werden
5. Thumbs werden per mediamanager ausgegeben 
6. Inline styles entfernt

@tyrant88 ich melde mich wenn hier wieder was funktioniert  😂

Die Entwicklung findet in der Branch DEV statt

**Comment by tyrant88** [comment]
Huch ganz vergessen zu antworten: Ja, super! Danke schon mal.

**Comment by tbaddade** [comment]
> Alles was sonst nicht mehr funktioniert habe ich entfernt

Kannst du kurz notieren, was entfernt wurde?

Wohin geht es mit Feeds? Liest sich so, als ob einiges umgebaut wird.

**Comment by skerbis** [comment]
@tbaddade 
den ganzen Facebook-Rums habe ich entfernt. 
Der Facebook-Vendor lässt sich auch eh nicht mehr aktualisieren.

**Comment by skerbis** [comment]
Ich habe Feeds soweit startbereit. Was ich nicht testen kann ist, was passiert wenn man ein Update durchführt von einer Version in der Facebook, Insta und Twitter eingebunden sind. Daher möchte ich ein Update von einer vorherigen Version unterbinden. 

Ich habe keine zuverlässigen, aktuellen Vendoren gefunden die diese Funktionalität zuverlässig und einfach zurückbringen. 

Bitte testet den aktuellen Stand: 

@tyrant88  @tbaddade

**Comment by skerbis** [comment]
alles klar. Finde auch keine Probleme mit PHP 8.x. , würde dann schon mal eine Beta rausjagen, wenn's für dich passt @tyrant88 .

**Comment by tyrant88** [comment]
du brauchst nicht auf mich warten, ich will dich nur unterstützen.

**Comment by skerbis** [comment]
4.0 erledigt
