### ISSUE TITLE
Vendor Konflikt

### ISSUE THREAD

**Issue by tyrant88** [FriendsOfREDAXO/feeds#194]
vereinfacht: wenn du mal `bin/console` aufrufst, gibts einen Error.
Weil in feeds/vendor nochmal die synfony/console drin ist - das beißt sich.
Ich habe schon mit @gharlan  geschnackt, da sind allgemein viele vendors drin, wo uns nicht so ganz klar ist, ob die wirklich benötigt werden.

Vielleicht kannst du @skerbis da einfach noch mal drüber schauen, ob das alles so ist wie gedacht.

**Comment by skerbis** [comment]
Ja. Cool wäre wenn man das irgendwie mit den core libraries abgleichen könnte und so eine exclude Liste hätte

**Comment by tyrant88** [comment]
Release 4.0.1 behebt das Problem. Sehr gut!
