### ISSUE TITLE
Fehler beim Klick auf "Stream abrufen" nach Update von 4.0.2 auf 4.0.3

### ISSUE THREAD

**Issue by brandes-webdesign** [FriendsOfREDAXO/feeds#197]
Bei mir kommt ein Fehler beim Klick auf "Stream abrufen" nach Update von 4.0.2 auf 4.0.3.

Class "GuzzleHttp\Client" not found

IN Datei: 
......redaxo/src/addons/feeds/lib/stream/rss.php

Zeile 32: 
        $client = new \FeedIo\Adapter\Http\Client(new GuzzleHttp\Client());
        
Ich hab das Problem bei zwei Webseite, die bei unterschiedlichen Providern sind.

**Comment by skerbis** [comment]
@brandes-webdesign bitte updaten auf 4.0.4 ... guzzle wird nicht mehr mitgeliefert. Ich habe jetzt auf den http client von symphony umgestellt.
