### ISSUE TITLE
RSS feed plugin importiert gelinkte Mediendateien

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/feeds#31]
Wenn ich das RSS feed plugin einsetze, um zB Podcast-Feeds einzulesen, habe ich das Problem, dass direkt die MP3-Dateien mit gezogen werden. Es wäre gut, wenn es einen switch o.ä. gäbe, um das zu verhindern und stattdessen die Media-URL einzusetzen.

**Comment by skerbis** [comment]
Das ist so beabsichtigt

**Comment by alexplusde** [comment]
@cukabeka du kannst im Zweifel das RSS-Feed duplizieren und für deine Bedürfnisse abwandeln.
