### ISSUE TITLE
RSS importiert nicht alle Felder

### ISSUE THREAD

**Issue by dtpop** [FriendsOfREDAXO/feeds#33]
Wenn in einem RSS Feed weitere Felder wie beispielsweise

```
<category>
<![CDATA[ Kategorie eins ]]>
</category>
<category>
<![CDATA[ Kategorie 2 ]]>
</category>
<category>
<![CDATA[ Noch eine Kategorie ]]>
</category>
```

vorkommen, so werden diese Daten nicht importiert. Wäre es möglich _alle_ Daten ins Feld "Inhalt ungefiltert" zu importieren?

**Comment by gharlan** [comment]
"Inhalt ungefiltert" ist für was anderes, da ist der eigentliche Text drin, aber im Originalformat (evtl. mit HTML-Tags etc.).
Es gibt aber ein Feld `raw`, da sind die Rohdaten als ganzes drin. Im Falle von RSS also als XML.

**Comment by dtpop** [comment]
Danke Gregor, ich sollte eher mal in die Datenbank schauen bevor ich Issues schreibe. - dennoch - das Feld raw enthält in meinem Falle nur leere category Einträge:

**Comment by dtpop** [comment]
Mir ist das jetzt gelungen alle Felder zu importieren, allerdings mit einem Patch in der Security.php

**Comment by dtpop** [comment]
Mir ist es jetzt gelungen alle Felder zu importieren, allerdings mit einem Patch in der Security.php
Zeile 68
`        $result = $dom->loadXml($xml, LIBXML_NONET);
`
ersetzt durch
`        $result = $dom->loadXml($xml, LIBXML_NOCDATA);
`
außerdem in der rss.php
`        $item->setRaw($rssItem);
`
an den Anfang der foreach Schleife setzen.

**Comment by alexplusde** [comment]
Da die security.php von einem Vendor stammt, weiß ich nicht, wie man das hier lösen kann. 

Auch hat sich wohl noch was am Code geändert. @skerbis @dtpop könnt ihr nachprüfen, ob das Problem überhaupt noch existiert?
https://github.com/zendframework/ZendXml/blob/fdd042359251c90902a741d4952e3b3e68025902/src/Security.php#L119-L124

Es sieht so aus, als könne man nun an anderer Stelle weitere Parameter wie `LIBXML_NOCDATA` mitgeben.

@dtpop Warum man `$item->setRaw($rssItem);` an den Anfang setzen müsste, erschließt sich mir nicht.

**Comment by alexplusde** [comment]
edit: scheint wohl die Zeile hier zu sein:
https://github.com/zendframework/ZendXml/blob/eceab37a591c9e140772a1470338258857339e00/src/Security.php#L70

Kann aber nicht sehen, dass scanString() überhaupt aufgerufen wird:

https://github.com/zendframework/ZendXml/blob/eceab37a591c9e140772a1470338258857339e00/src/Security.php#L42

**Comment by alexplusde** [comment]
@dtpop evtl. wurde das durch ein vendor-Update durch @skerbis behoben. Wo finde ich denn eine URL zum testen mit den Daten, die problematisch waren/sind?

**Comment by alexplusde** [comment]
Die Vendoren wurden aktualisiert. Ich habe es mit https://www.feedforall.com/blog-feed.xml getestet und da sind CDATA-Infos drin, die auch erfolgreich ausgeblendet werden und der Inhalt importiert wird. 

Da ich hier und auf Slack keine Antwort erhalte, schließe ich hier.
