### ISSUE TITLE
Automatisches Löschen alter Einträge in der DB

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/feeds#39]
Für den einen oder anderen Stream könnte es nützlich sein, die Menge der Datensätze zu begrenzen. 
z.B.: Bei einem RSS-Feed der nur aktuelle Links zeigen soll.

**Comment by tbaddade** [comment]
Dann sollte die Ausgabe deines Feeds die Anzahl bzw. die aktuellen Links nur liefern.

**Comment by skerbis** [comment]
Klar habe ich so gemacht. Aber wird die REDAXO-DB nicht unnötig überfüllt, wenn ich nur 10 Links brauche am Tag?

**Comment by alexplusde** [comment]
Ein Aufräum-Cronjob würde es tun. Könnte man abstrahieren. Also nach dem Motto:
- Parameter Datenbank
- Parameter Zeitstempel-Feld
- Parameter Delta / Zeitabstand

**Comment by cukabeka** [comment]
Finde ich eine sehr gute Idee, das abstrahiert mit einem Cronjob-Plugin zu lösen.

**Comment by alexplusde** [comment]
Auch die Möglichkeit, Streams auf Knopfdruck zu leeren, wäre für Entwicklungszwecke super.

**Comment by alexplusde** [comment]
Ich habe in #124 für die Doku nun ein Beispiel dazu, wie das super einfach geht - wahrscheinlich besser, als man es je in Einstellungen pro Stream oder insgesamt machen könnte.
