### ISSUE TITLE
RSS : Whoops - wenn der Stream abgerufen wird und die Url einen 404 sendet

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/feeds#40]

**Comment by alexplusde** [comment]
Generell werden Konfigurations-Fehler mit einem Whoops ausgegeben und nicht mit einer Fehlermeldung innerhalb von REDAXO. Hier am Beispiel Facebook:

![image](https://user-images.githubusercontent.com/3855487/67704160-e69d2a80-f9b4-11e9-8141-2721c2419de1.png)

**Comment by alexplusde** [comment]
Falls möglich, bitte PR testen / reviewen @tbaddade
