### ISSUE TITLE
Feeds-Stream in YForm-Tabelle importieren

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/feeds#43]
Ich finde die Funktion von YFeed mit dem selbständigen Aktualisieren von Datensätzen echt klasse. Was fehlt, ist in meinen Augen, eine andere Zieltabelle als die von YFeed angeben zu können und mit anderen Feldern als denen von YFeed zu arbeiten.

Ein Beispiel: Bandsintown bietet eine API, mit der man Tickets einer Band als Liste ausgeben kann. Diese will ich geocodieren. Ich könnte einen YFeed-Stream erstellen, der mir die Daten abruft, allerdings gibt es in YFeed nicht die vorgesehenen Felder für bspw. Str, PLZ, Ort und Ticket-URL und die Geocoding-Funktion steckt ja in YForm.

Wie sollte ich das aktuell lösen? Ich würde aktuell YFeed außenvor lassen und nur über einen Cronjob gehen. Hätte aber gerne YFeed um diese API erweitert.

**Comment by alexplusde** [comment]
Ich sehe hier inzwischen viel Überschneidung mit dem Issue #74 und ansonsten gibt es immer noch die Möglichkeit, das über YOrm oder rex_sql zu lösen, wenn es nur um den Import geht. Das Issue lasse ich offen, damit es dokumentiert werden kann.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/feeds/commit/58034bd6ab25eb22ac36305f51bdb70e521ccb7c
