### ISSUE TITLE
Facebook Feeds leider ohne Bilder

### ISSUE THREAD

**Issue by gut8er** [FriendsOfREDAXO/feeds#44]
Leider werden von Facebook keine Bilder mehr übermittelt.

**Comment by alexplusde** [comment]
Hallo gut8er, ich habe das Addon ebenfalls im Einsatz und kann das nicht bestätigen. Es kommt darauf an, wie der Facebook-Post aussieht. Bildergalerien werden meines Wissens nicht erkannt/unterstützt, ein einzelner Post mit Bild jedoch schon.

**Comment by gut8er** [comment]
Hi Alex,

also mit einer Bildergalerie hat es nichts zu tun. Eher damit das der Knotenpunkt irgendwie anders ist als erwartet. Ich habe es jetzt mit folgender Anpassung zum laufen gebracht:

facebook_feed.php

`$attachments = $facebookItem->getField('attachments');
            if ($attachments) {

                /** @var Facebook\GraphNodes\GraphNode $attachment */
                foreach ($attachments as $attachment) {

                    dump($attachment);

                    /*if ('photo' !== $attachment->getField('type') || !$media = $attachment->getField('media')) {
                        continue;
                    }*/

                    /** @var Facebook\GraphNodes\GraphNode $image */
                    $image = $attachment->getField('media')->getField('image')->getField('src');
                    if ($image) {
                        $item->setMedia($image);
                        break;
                    }
                }
            }`

somit musste ich hier etwas weiter nach unten: `$image = $attachment->getField('media')->getField('image')->getField('src');`

ich vermute mal hier müsste man eine rekursive Funktion einbauen die einfach sucht bis sie ein SRC findet? Weil meine jetzige Lösung ist ja zum einen nicht Updatefähig und auch net wirklich schön.

Der Originalcode sah wie folgt aus Zeilen 84 bis 99:

`if ($attachments) {
                /** @var Facebook\GraphNodes\GraphNode $attachment */
                foreach ($attachments as $attachment) {

                    if ('photo' !== $attachment->getField('type') || !$media = $attachment->getField('media')) {
                        continue;
                    }

                    /** @var Facebook\GraphNodes\GraphNode $image */
                    $image = $media->getField('image');
                    if ($image) {
                        $item->setMedia($image->getField('src'));
                        break;
                    }
                }
            }`

Aber mit diesem Code kam wie gesagt gar kein Bild mit. Erst mit meiner Anpassung und eine Galerie kann ich in keinem der Posts finden. Oder habe ich doch noch etwas übersehen oder falsch gemacht? Auf dieser Seite ganz unten haben ich es mal eingebaut "Social Reader"

**Comment by gut8er** [comment]
Jetzt bin ich im Slack ;)

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/feeds/releases/tag/2.0.0
