### ISSUE TITLE
Facebook: Problem mit emoji

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/feeds#49]
Titel und RAW werden nur bis zum ersten Emoji ausgelesen. Ist das ein Kodierungsproblem? Was ist zu tun?

**Comment by alexplusde** [comment]
1. betroffene Felder in der Datenbank auf utf8mb4 stellen, evtl. auch die Tabelle
2. Diesen Kommentar zur `sql.php` befolgen (Achtung, nicht updatesicher): https://github.com/redaxo/redaxo/issues/1231#issuecomment-325206786

**Comment by alexplusde** [comment]
(3. hier das Issue pushen: https://github.com/redaxo/redaxo/issues/638)

**Comment by godsdog** [comment]
Ich habe mir quick and dirty in der facebook_feed.php die Lib "php-emoji" (https://github.com/iamcal/php-emoji/) eingebaut:

`
$item->setContentRaw(emoji_unified_to_html($facebookItem->getField('message')));
$item->setContent(strip_tags(emoji_unified_to_html($facebookItem->getField('message'))));
`

So werden die Emotions im DB Feld "Inhalt" raus gefiltert und im "RAW" Feld mit 
`<span class="emoji-outer emoji-sizer"><span class="emoji-inner emoji1f609"></span></span>`
ersetzt. So musste in nicht auf utf8mb4 umstellen.

**Comment by alexplusde** [comment]
Das Problem wird gelöst, indem die Felder für Content und RAW auf utf8mb4 umgestellt wird.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/feeds/blob/a89bc37b7f4984e54ad76d77b0e58f889ec317f7/install.php#L51
