### ISSUE TITLE
Pinterest-Stream/Streams hinzufügen

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/feeds#5]

**Comment by alexplusde** [comment]
https://developers.pinterest.com/docs/api/overview/?

ich kenne mich mit Pinterest überhaupt nicht aus - da gibt's wie bei Twitter auch Profile, Hashtags und Co? Gibt's da etwas Internes, auf dem ich aufbauen könnte? @dergel

**Comment by alexplusde** [comment]
@dergel es gibt ein RSS-Feed für Boards und User.
https://developers.pinterest.com/docs/getting-started/introduction/?
