### ISSUE TITLE
Instagram manuelle Einstellung für API Nutzung

### ISSUE THREAD

**Issue by VIEWSION** [FriendsOfREDAXO/feeds#51]
Es wäre gut wenn man bei Instagram je Feed einstellen könnte welche API genutzt werden soll.

**Comment by skerbis** [comment]
Weiß nicht was hier gemeint ist. Ist das Thema noch aktuell?

**Comment by VIEWSION** [comment]
Es gab da mal sowas wie eine offizielle Instagram API und eine "inoffizielle Version" ganz ohne API-Key. Da es inzwischen kaum noch möglich ist an einen offiziellen API-Schlüssel zu kommen, werden die meisten wohl auf den zweiten Weg setzen. Aber dafür war es wohl mal gemeint... also ein Switch welcher Weg genutzt werden soll... und zwar auf Feed-Ebene und nicht generell.

**Comment by skerbis** [comment]
Danke für die Info
