### ISSUE TITLE
Username

### ISSUE THREAD

**Issue by VIEWSION** [FriendsOfREDAXO/feeds#52]
Bei Posts ist es eigentlich üblich den Username anzuzeigen und nicht den vollen Namen. Daher wäre es gut wenn man zusätzlich zum author (fullName) auch den username (wo es einen gibt) abrufen würde.

**Comment by tbaddade** [comment]
@VIEWSION Im Feld `raw` müsste der Username mit enthalten sein.

**Comment by VIEWSION** [comment]
@tbaddade bei twitter ja - Instagram nicht. Im raw bei Instagram ist komischerweise aber auch nicht der fullName zu finden. Fehlt da was? Aber als eigenes Tabellenfeld wäre es schon praktischer... kann man leichter suchen/filtern und braucht bei der Ausgabe nicht das raw parsen.

**Comment by tbaddade** [comment]
@VIEWSION Eigenes Feld wäre sicherlich sinnvoll. Magst du dich dem Ganzen annehmen und einen PR erstellen?

**Comment by VIEWSION** [comment]
@tbaddade kurzfristig bekomm ich das nicht unter.
Auf die Schnelle habe ich in der instagram.php bei mir das
`$item->setAuthor($owner->getFullName() ?: null);`
durch
`$item->setAuthor($owner->getUsername() ?: null);`
ersetzt.

Aber wenn ich mal wieder etwas Luft habe, kann ich das schon "richtig" machen ;)

**Comment by alexplusde** [comment]
@VIEWSION wie schaut's inzwischen aus mit Luft? Und welche Lösung wird hier bevorzugt: Ein eigenes author-Feld? Oder das Aufnehmen in das raw-Feld?

**Comment by skerbis** [comment]
@alexplusde raw

**Comment by VIEWSION** [comment]
@alexplusde sorry... Kein Land in Sicht. Bis auf weiteres muss ich mich hier ausklinken. Sollte ich mal wieder ein Projekt mit dem AddOn haben, würde ich es wahrscheinlich mit angehen - aber wartet bitte nicht drauf ;)

**Comment by alexplusde** [comment]
In `raw` war es nicht ohne Weiteres möglich, da das eigentliche Objekt den Autor nicht enthält - deswegen war ich so frei, und habe das jetzt für Instagram und Twitter in eine extra Spalte gelegt.
