### ISSUE TITLE
Instagram Abruf dauert recht lange

### ISSUE THREAD

**Issue by VIEWSION** [FriendsOfREDAXO/feeds#57]
Bei Instagram (ich nutze die alternative Version ohne Token) dauert der Abruf von Posts (tag) recht lange... können schon mal 20 Sekunden und mehr sein. Is natürlich blöd wenn das über einen Cronjob regelmäßig gemacht wird. Weiß jemand woran das liegt? Kann man da was machen?

**Comment by alexplusde** [comment]
Server-Cronjob verwenden, dann stört's nicht so.
