### ISSUE TITLE
Facebook Feed ohne Album Bilder

### ISSUE THREAD

**Issue by clicksports** [FriendsOfREDAXO/feeds#70]
Hallo,

wie ich festgestellt habe ist es aktuell nicht möglich Bilder aus einem Album aus dem Facebook feed zu bekommen.

Ich hätte hier eine Lösung die Funktioniert:

```
// fetch subattachments
foreach ($attachments as $attachment) {
    if ($attachment->getField('type') === 'album') {
         $subAttachments = $attachment->getField('subattachments');
         break;
    }
}

$attachments = isset($subAttachments) ? $subAttachments : $attachments;
```

**Comment by alexplusde** [comment]
Kannst du das evtl als pull request direkt beisteuern?

**Comment by clicksports** [comment]
Leider kann ich keinen Pull Request erstellen...

**Comment by clicksports** [comment]
Aber ich hab in der Datei: /lib/stream/facebook_feed.php

den Code in die Zeile: 85 eingefügt

**Comment by clicksports** [comment]
@alexplusde ?

**Comment by alexplusde** [comment]
@clicksports sorry, muss sich dann jemand anderes darum kümmern.

**Comment by skerbis** [comment]
@clicksports du kannst das doch einfach als pr einreichen. Einfach die Datei hier https://github.com/yakamara/redaxo_yfeed/blob/master/lib/stream/facebook_feed.php editieren. Es wird dann automatisch ein fork erzeugt aus dem du den pr dann starten kannst.

**Comment by clicksports** [comment]
@skerbis Ah ok nice :)

**Comment by clicksports** [comment]
https://github.com/yakamara/redaxo_yfeed/pull/72

**Comment by skerbis** [comment]
Danke @gegerino
