### ISSUE TITLE
Facebook Veranstaltungen

### ISSUE THREAD

**Issue by simonsinus** [FriendsOfREDAXO/feeds#71]
Ist auch geplant den Event Feed einzubinden?

**Comment by alexplusde** [comment]
@simonsinus hast du damit evtl schon Erfahrung? Ein Feed einlesen bzw. ein eigenes Feed-Schema definieren ist recht schnell gemacht. Momentan ist nichts geplant.

**Comment by simonsinus** [comment]
Also konkret meine ich den Facebook Event-Feed. 
Das habe ich schonmal hinbekommen. Aber ich weiß nichtmal ob das Facebook so noch zulässt.

**Comment by simonsinus** [comment]
Ich habe da mal was gemacht:

`<?php


$page_id = 'xxx';
$access_token2 = 'xxx';

$json_object2 = @file_get_contents('https://graph.facebook.com/PavillonOppenau/events/?fields=description,name,start_time,id,link&access_token='.$access_token2);


$fbdata2 = json_decode($json_object2);
$data2 = $fbdata2->data;

$post2s ='';
foreach ($data2 as $post2)
{
$id = $post2->id;

$full_picture = '<img style="width:40%;height:auto;position:relative;" src="http://graph.facebook.com/'.$id.'/picture?type=large" />';

$title = "";
if($post2->start_time!="") {
$zeit = $post2->start_time;
$time = strtotime($zeit);

$datum = date('d.m.Y', $time);
$uhrzeit = date('G:i', $time);
}
if($time > strtotime('today midnight')) {
$title = $post2->name;

$post2s .= '<div class="tinymcewysiwyg">';

$post2s .= '<h2><a href="http://www.facebook.de/events/' . $post2->id . '" target="_blank">' . $title. '</a></h2>';
$post2s .= '<p>'.$full_picture.'</p>';
$post2s .= '<h3>' . $datum  . ' ab '.$uhrzeit.' Uhr</h3>';
#$post2s .= '<p>'. $post2->description .'</p>';
$post2s .= '<a href="http://www.facebook.de/events/' . $post2->id . '" target="_blank">mehr...</a>';

$post2s .= '</div>';
$post2s .= '<div class="clr"></div>';
}
}
echo $post2s;
file_put_contents ('events.html',$post2s);
?>`

**Comment by alexplusde** [comment]
@simonsinus kannst du dir meinen PR dazu mal anschauen? 

Ich bekomme die Bilddaten noch nicht ausgelesen und der Import ist auf 25 Veranstaltungen beschränkt, wie es aktuell aussieht - aber es gibt auch die Möglichkeit, Seite 2/3 abzurufen.

**Comment by alexplusde** [comment]
closed in #122
