### ISSUE TITLE
Feeds in yform umsetzen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/feeds#74]
Aktuell ist es nicht möglich yFeed-Tabellen in yform zu importieren. Daher kann z.B. beim Vimeo feed nicht das yform widget verwendet werden um sich ein Video aussuchen zu können. 

> Migration für `rex_yfeed_item` ist fehlgeschlagen. Fehler: Error while executing statement "SELECT * FROM `'rex_yfeed_item'` WHERE `'status'` NOT IN (0, 1) LIMIT 1"! SQLSTATE[42S02]: Base table or view not found: 1146 Table 'XXXX.'rex_yfeed_item'' doesn't exist

**Comment by alexplusde** [comment]
Ein weiterer Vorteil ist, dass man zusätzliche Felder hinzufügen kann, wenn man diese für eigene Streams benötigt, z.B. bei #35 - auch #56 Status-Schalter mittels Addon yform_usability wäre dann möglich und man muss so das Rad nicht neu erfinden.

**Comment by skerbis** [comment]
Es bleibt wie es ist. Die Tabelle kann jetzt ohne Schwierigkeiten in YForm informiert werden und man kann den Redakteuren dann in YForm ein reduziertes oder erweitertes Formular zur Verfügung stellen. 
Da die Tabellen nun mit Ensure sichergestellt sind können auch in YForm neue Spalten hinzugefügt werden, wenn erforderlich.

**Comment by alexplusde** [comment]
Du meinst über das Migrieren? Würde ich zumindest in den Docs erwähnen.

**Comment by skerbis** [comment]
Ja 👍

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/feeds/issues/43

**Comment by tbaddade** [comment]
Das Migrieren funktioniert bereits. Ich würde einen generellen Umbau zu YForm nicht machen.

**Comment by alexplusde** [comment]
@tbaddade was spricht dagegen?
