### ISSUE TITLE
Vendors

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/feeds#78]
YFeed installiert sehr viele vendors mit - gibt es da evtl. Streams, die Yakamara zusätzlich veröffentlichen könnte? Ist es beabsichtigt, dass diese aktuell mit installiert werden?

![image](https://user-images.githubusercontent.com/3855487/50522876-6e808280-0acd-11e9-8ecb-409290ba25aa.png)

**Comment by skerbis** [comment]
Die meisten Abhängigkeiten kommen von picofeed. So lange das im Einsatz ist / bleibt wird sich vorerst nichts daran ändern.

**Comment by alexplusde** [comment]
Ich kann mich nicht erinnern, dass das ausgewählt werden kann...

**Comment by skerbis** [comment]
RSS
