### ISSUE TITLE
Warning im syslog - Twitter

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/feeds#80]
You should not use non-secure socket connections while connecting to "pbs.twimg.com"! |  
-- | --
redaxo/src/core/lib/util/socket/socket.php | 269

**Comment by skerbis** [comment]
Kein TLS verwendet?

**Comment by alexplusde** [comment]
Keine Ahnung, wie hätte ich das forcieren können?

**Comment by skerbis** [comment]
ok wir konnten das Warning reproduzieren ... 

https://github.com/FriendsOfREDAXO/feeds/blob/9afa391224e26ff1485bf540282ec6c659d46220/lib/helper.php#L24

https://github.com/redaxo/redaxo/blob/a094ec31288807c044b47b5d0a453128efed138c/redaxo/src/core/lib/util/socket/socket.php#L84-L89

@gharlan kann man SSL erzwingen? Non-ssl sollte eh keiner dieser Feeds mehr sein, denke ich.

**Comment by alexplusde** [comment]
Es gibt eine eigene Property mit der https-URL dafür.
