### ISSUE TITLE
Feeds blockiert Backup-Cronjob

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/feeds#89]
Durch die Menge an Daten, die z.B. bei Facebook-Posts mit Bildern in der Datenbank liegen, wird der Backup-Cron nicht mehr ausgeführt.

Man müsste die Items ausschließen können im Backup-Cronjob

**Comment by skerbis** [comment]
Aus meiner Sicht müsste das im Backup-AddOn angepasst werden.

**Comment by alexplusde** [comment]
Ich fürchte auch. Search_it könnte das im Übrigen auch gebrauchen, Tabellen-Inhalte auszuschließen

**Comment by skerbis** [comment]
https://github.com/redaxo/redaxo/issues/2754
