### ISSUE TITLE
[WIP] Letztes yFeed-Release / Migrationsskript

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/feeds#93]
Vor der Umstellung auf Feeds sollte es vlt nochmal ein getestetes Release von YFeed geben, dann könnte man Feeds als neue Major-Version rausgeben und es sich vielleicht sparen, 100% rückwärtskompatibel zu sein. Stattdessen ein Migrationsskript.

Das Skript müsste die Profile und Items in der Datenbank kopieren, sowie Cronjobs und Medien Manager Profile updaten, jedoch nicht Templates/Module

**Comment by tbaddade** [comment]
> Das Skript müsste die Profile und Items in der Datenbank kopieren

das wäre nicht wirklich sinnvoll. Die Items nehmen den meisten Speicherplatz der Datenbank in Anspruch.

**Comment by alexplusde** [comment]
@tbaddade wie würdest du das Y loswerden?

**Comment by alexplusde** [comment]
Vielleicht war ich auch nicht klar in der Formulierung: Tabelle umbenennen geht ja auch.

**Comment by skerbis** [comment]
Mir ist auch noch nicht klar wie ein „Upgrade“ zu feeds erfolgen kann. Yfeed löscht die Tabelle wenn es deinstalliert wird. Die Installation von feeds könnte parallel erfolgen und dann yfeed nach der Umbenennung der Tabelle deinstallieren. Ist das möglich @gharlan @tbaddade ?

**Comment by alexplusde** [comment]
Eine mögliche Idee:

Schritt 1: Letzte yFeed-Version erfordert allererste Feeds-Version, aber Feeds tut nichts, solange YFeed installiert ist.
Schritt 2: Deinstallation von yFeed verschiebt die Inhalte zu Feeds, wenn vorhanden.
Schritt 3: nächste Feeds-Version blockiert Installation parallel zu YFeed

**Comment by gharlan** [comment]
Also ich bin mir unsicher, was der beste und zugleich nicht zu komplizierte Weg ist.

Am liebsten wäre mir, kein yfeed-Release mehr zu machen. Denn es sind ja jetzt auch schon neue Features gemerged und so, und die würde ich eigentlich nicht mehr unter dem Namen releasen wollen. Falls wir noch ein yfeed-Release machen würden, würde ich es lieber vom letzten Release-Stand aus machen. 

Den Weg von @alexplusde finde ich bisschen heikel. Wenn dann versehentlich jemand eine vorherige YFeed-Version deinstalliert, weil es ja so erläutert ist als Übergang (und vergisst vorher zu updaten), dann verliert er seine Daten.

Ich fände eigentlich am besten, wenn Feeds beim Installieren schaut, ob die yfeed-Tabellen existieren, und dann diese dupliziert zu den eigenen. Feeds würde dann also einfach parallel zu yfeed laufen, und man kann dann, wenn alles passt, yfeed deinstallieren.

Ich kann allerdings nicht ganz einschätzen, wie viele Daten das so sein können.

**Comment by tbaddade** [comment]
> Ich kann allerdings nicht ganz einschätzen, wie viele Daten das so sein können.

**Beispiel**

| Gesamt | davon YFeed |
| --- | --- | 
| 113 MB | 111 MB |

**Comment by dergel** [comment]
Gregors Weg klingt für mich am besten. Wenn es viele Daten sind, dann sind es eben viele :)

**Comment by skerbis** [comment]
Kann man mit rex_sql_table eine Tabelle kopieren? @gharlan 
Kurzes Snippet würde mir helfen. 
Ich probiere dann die Lösung mit dem Parallelbetrieb

**Comment by gharlan** [comment]
Die Tabellenstruktur würde ich nicht aus der yfeed-Tabelle generieren, sondern normal bei Installation anlegen. Und dann nur ggf. die Daten kopieren.

Ungetestet, so in der Art würde ich es probieren:

```php

$table = rex_sql_table::get('rex_feeds_stream');
$exists = $table->exists();

$table
    ->ensureColumn(...)
    ->ensureColumn(...)
    ->ensure();

rex_sql_table::get('rex_feeds_item')
    ->ensureColumn(...)
    ->ensureColumn(...)
    ->ensure();

if (!$exists && rex_addon::get('yfeed')->isAvailable()) {
    $sql = rex_sql::factory();
    $sql->setQuery('INSERT INTO rex_feeds_stream SELECT * FROM rex_yfeed_stream');
    $sql->setQuery('INSERT INTO rex_feeds_item SELECT * FROM rex_yfeed_item');
}
```

**Comment by skerbis** [comment]
Top! Danke

**Comment by gharlan** [comment]
Bei den INSERT SELECT befehlen sollte man ggf. besser explizit die Spalten angeben. Damit es keinen Fehler gibt, wenn wir neue Spalten ergänzen und so.

**Comment by skerbis** [comment]
hmm... das scheint so nicht zu funktionieren. Ich bekomme folgende Meldung

> AddOn feeds konnte aus folgendem Grund nicht installiert werden:
SQL error: Error while executing statement "INSERT INTO rex_feeds_stream SELECT namespace,type,type_params,title,image,etag,last_modified,status,createuser,updateuser,createdate,updatedate FROM rex_yfeed_stream"! SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 1

**Comment by skerbis** [comment]
@gharlan der von dir genannte Weg hat bei mir nicht funktioniert. 

```php
if (rex_addon::get('yfeed')->isAvailable()) {
 $sql = rex_sql::factory();
 $sql->setQuery('CREATE TABLE IF NOT EXISTS ' . rex::getTablePrefix() . 'feeds_stream LIKE ' . rex::getTablePrefix() . 'yfeed_stream');  
 $sql->setQuery('INSERT ' . rex::getTablePrefix() . 'feeds_stream SELECT * FROM ' . rex::getTablePrefix() . 'yfeed_stream') ; 
 $sql->setQuery('CREATE TABLE IF NOT EXISTS ' . rex::getTablePrefix() . 'feeds_item LIKE ' . rex::getTablePrefix() . 'yfeed_item');  
 $sql->setQuery('INSERT ' . rex::getTablePrefix() . 'feeds_item SELECT * FROM ' . rex::getTablePrefix() . 'yfeed_item') ; 
}
```
klappt dagegen. 

leider führt

```php
$table = rex_sql_table::get('rex_feeds_stream');
$exists = $table->exists();
```

dass die Tabelle direkt angelegt wird. 
Wie kann ich prüfen ob die Tabelle bereits existiert bzw. nicht existiert bevor ich diese evtl. aus yfeed heraus erstmal generiere und dann im nachfolgenden Code auf per ensure aktualisiere?

**Comment by skerbis** [comment]
ich habe es nun so gelöst: 

if (rex_addon::get('yfeed')->isAvailable() && !$this->hasConfig('yfeed_migration')) {
 $sql = rex_sql::factory();
 $sql->setQuery('CREATE TABLE IF NOT EXISTS ' . rex::getTablePrefix() . 'feeds_stream LIKE ' . rex::getTablePrefix() . 'yfeed_stream');  
 $sql->setQuery('INSERT ' . rex::getTablePrefix() . 'feeds_stream SELECT * FROM ' . rex::getTablePrefix() . 'yfeed_stream') ; 
 $sql->setQuery('CREATE TABLE IF NOT EXISTS ' . rex::getTablePrefix() . 'feeds_item LIKE ' . rex::getTablePrefix() . 'yfeed_item');  
 $sql->setQuery('INSERT ' . rex::getTablePrefix() . 'feeds_item SELECT * FROM ' . rex::getTablePrefix() . 'yfeed_item') ; 
 $this->setConfig('yfeed_migration','1');   
}

**Comment by skerbis** [comment]
Als nächstes müssen noch bestehende Configs übertrafen werden, wie API-Keys und Secrets etc.

**Comment by skerbis** [comment]
Die Configs werden nun auch übernommen

**Comment by gharlan** [comment]
> leider führt
> 
> ```
> $table = rex_sql_table::get('rex_feeds_stream');
> $exists = $table->exists();
> ```
> 
> dazu, dass die Tabelle direkt angelegt wird.

Also das kann ich nicht bestätigen, bei mir ist das nicht so. Sollte so auch nicht sein.

**Comment by skerbis** [comment]
Aber der jetzige Weg funktioniert ja auch soweit. Damit ist auch sichergestellt dass die Tabelle einmal übernommen wird.

**Comment by skerbis** [comment]
erledigt
