### ISSUE TITLE
Ical als Feed 

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/feeds#96]

**Comment by alexplusde** [comment]
Könnte in https://github.com/alexplusde/sked_ics demnächst kommen. Ich verspreche nichts. ;)

**Comment by skerbis** [comment]
Ich bin mir auch nicht sicher ob es wirklich Sinn macht. Oder ob's viel besser in Sked aufgehoben wäre

**Comment by skerbis** [comment]
Ist eher was für Sked

**Comment by alexplusde** [comment]
(finde ich auch)
