### ISSUE TITLE
Vendoren

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/feeds#97]
Macht es Sinn die Vendoren mit in das Repo zu legen? 
Die GitHub Releases sind aktuell ohne Vendoren. 
Im installer sind die Vendoren natürlich dabei. 

@gharlan 
Wie siehst du das?

**Comment by gharlan** [comment]
Hat Vor- und Nachteile. Ein Nachteil der aktuellen Variante hast du schon genannt, die GitHub Releases.
Glaube, der Vendor-Ordner ist hier recht groß. Das ist halt der Vorteil der aktuellen Variante, dass man nicht solche großen Commits bei Updates bekommt mit den ganzen Vendor-Updates.

Ich denke, wenn ich es selbst weiter betreuen würde, würde ich bei der aktuellen Variante bleiben.
Aber kann auch verstehen, wenn du dich anders entscheidest (wie gesagt, Vor- und Nachteile).

**Comment by skerbis** [comment]
Danke.  Das hast Du gewiss Recht. In der README sollte man darauf hinweisen, dass dies keine vollständigen Releases hier sind

**Comment by schuer** [comment]
Das Installer-Release könntest du dem GitHub-Release als Attachment anhängen, @skerbis. Das macht REDAXO selbst auch, siehe etwa https://github.com/redaxo/redaxo/releases/tag/5.7.1 oder auch AddOns wie bloecks: https://github.com/FriendsOfREDAXO/bloecks/releases/tag/1.4.0
